#ifndef CUBLAS_ERRORS_H
#define CUBLAS_ERRORS_H

#define CUBLAS_RESULTS \
	RES(CUBLAS_STATUS_SUCCESS, 0) \
	RES(CUBLAS_STATUS_NOT_INITIALIZED, 1) \
	RES(CUBLAS_STATUS_ALLOC_FAILED, 3) \
	RES(CUBLAS_STATUS_INVALID_VALUE, 7) \
	RES(CUBLAS_STATUS_ARCH_MISMATCH, 8) \
	RES(CUBLAS_STATUS_MAPPING_ERROR, 11) \
	RES(CUBLAS_STATUS_EXECUTION_FAILED, 13) \
	RES(CUBLAS_STATUS_INTERNAL_ERROR, 14) \
	RES(CUBLAS_STATUS_NOT_SUPPORTED, 15) \
	RES(CUBLAS_STATUS_LICENSE_ERROR, 16)

#define STR(x) #x
#define RES(ENUM, VALUE) { VALUE, STR(ENUM) },
struct errValType { int value; const char *name; };
const errValType CUBLAS_RESULT_STR[] = { CUBLAS_RESULTS };
#undef RES

#endif
